CREATE TABLE person(
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, NAME VARCHAR (60) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE SHIRT(
ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, STYLE ENUM('t-SHIRT','POLO','DRESS')NOT NULL,COLOR ENUM('RED','BLUE','ORANGE','WHITE','BLACK')NOT NULL,OWNER SMALLINT UNSIGNED NOT NULL REFERENCES PERSON (ID),PRIMARY KEY(ID));

INSERT INTO PERSON VALUES (NULL, 'ANTONIO PAZ');
SELECT @LAST := LAST_INSERT_ID();
INSERT INTO SHIRT VALUES (NULL, 'POLO','BLUE',@LAST),(NULL, 'DRESS','WHITE',@LAST),(NULL, 't-SHIRT','BLUE',@LAST);

INSERT INTO PERSON VALUES (NULL, 'LILLIANA ANGELOVSKA');
SELECT @LAST := LAST_INSERT_ID();
INSERT INTO SHIRT VALUES (NULL, 'DRESS','ORANGE',@LAST),(NULL, 'POLO','RED',@LAST),(NULL, 'DRESS','BLUE',@LAST),(NULL, 't-SHIRT','WHITE',@LAST);

SELECT S.*
FROM PERSON P INNER JOIN SHIRT S ON S.OWNER = P.ID WHERE P.NAME LIKE '%LILLIANA%' AND S.COLOR <> 'WHITE';